FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["SmarterTickets.Web/SmarterTickets.Web.csproj", "SmarterTickets.Web/"]
COPY ["SmarterTickets.Core/SmarterTickets.Core.csproj", "SmarterTickets.Core/"]
RUN dotnet restore "SmarterTickets.Web/SmarterTickets.Web.csproj"
COPY . .
WORKDIR "/src/SmarterTickets.Web"
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SmarterTickets.Web.dll"]